- id: dongmanhuayuan
  name: dongmanhuayuan
  domain: 'https://www.dongmanhuayuan.com/'
  encoding: UTF-8

  # 是否是公共站点
  public: true
  # 是否需要代理
  proxy: false
  # 是否referer
  referer: 
  # 网站语言类型(英文 en ,中文 zh)
  language: 
  # render true/false
  render: 
  # parser (Rarbg/TNodeSpider/RenderSpider/不填写则使用默认spider)
  parser: 
  
  search:
    paths:
      - path: 'search/{keyword}'
        method: get
  torrents:
    list:
      selector: .uk-grid.uk-grid-collapse
    fields:
      id:
        selector: 'a[href*="/t/"]'
        attribute: href
        filters:
          - name: re_search
            args:
              - \d+
              - 0
      title:
        selector: span.uk-width-expand > a
        remove: 'em'
      details:
        selector: span.uk-width-expand > a[href*='/detail/']
        attribute: href
      download:
        detail:
          # xpath语法参考： https://blog.csdn.net/weixin_43718786/article/details/108504732 
          xpath: '//input[@id="magnet_two"]//@value'
      date_added:
        selector: .uk-width-small.uk-visible\@m
      size:
        selector: .uk-label > b
      # 种子数
      # seeders:
        # selector: td.peers > div.seed > span
      # 下载数
      # leechers:
        # selector: td.peers > div.leech > span
      # 完成数
      # grabs:
        # selector: td.peers > div.done > span
- id: hdpianyuan
  name: 高清片源网
  domain: 'https://www.hdpianyuan.com/'
  encoding: UTF-8

  # 是否是公共站点
  public: true
  # 是否需要代理
  proxy: false
  # 是否referer
  referer: 
  # 网站语言类型(英文 en ,中文 zh)
  language: 
  # render true/false
  render: 
  # parser (Rarbg/TNodeSpider/RenderSpider/不填写则使用默认spider)
  parser:

  search:
    paths:
      - path: 'search.htm?keyword={keyword}'
        method: get
  torrents:
    list:
      selector: ul.list-unstyled.threadlist > li
    fields:
      title:
        selector: 'div.media-body > div.subject > a[href*="source-"]'
      details:
        selector: 'div.media-body > div.subject > a[href*="source-"]'
        attribute: href
      download:
        detail:
          xpath: '//span[@id="link_text_span"]/text()'
      date_added:
        selector: 'div.media-body > div.subject > span:nth-child(2)'
      size:
        selector: 'div.media-body > div.subject > span:nth-child(1)'
      description:
        selector: span.filenamespan
      downloadvolumefactor:
        case:
          '*': 0
      uploadvolumefactor:
        case:
          '*': 1

- id: acg.rip
  name: acg.rip
  domain: 'https://acg.rip/'
  encoding: UTF-8

  # 是否是公共站点
  public: true
  # 是否需要代理
  proxy: false
  # 是否referer
  referer: 
  # 网站语言类型(英文 en ,中文 zh)
  language: 
  # render true/false
  render: 
  # parser (RenderSpider)
  parser: 
  
  search:
    paths:
      - path: '?term={keyword}'
        method: get
  torrents:
    list:
      selector: table.table-hover > tr
    fields:
      id:
        selector: 'a[href*="/t/"]'
        attribute: href
        filters:
          - name: re_search
            args:
              - \d+
              - 0
      title:
        selector: span.title > a
      details:
        selector: span.title > a
        attribute: href
      download:
        selector: td.action > a
        attribute: href
      date_added:
        selector: td.date > time
        attribute: datetime
      size:
        selector: td.size
      seeders:
        selector: td.peers > div.seed > span
      leechers:
        selector: td.peers > div.leech > span
      grabs:
        selector: td.peers > div.done > span
      downloadvolumefactor:
        case:
          '*': 0
      uploadvolumefactor:
        case:
          '*': 1

- id: mikantv
  name: MiKanTv
  # domain的(host,port)应该与id一对一
  domain: 'https://mikanime.tv/'
  encoding: UTF-8

  # 是否是公共站点
  public: true
  # 是否需要代理
  proxy: false
  # 是否referer
  referer:
  # 网站语言类型(英文 en ,中文 zh)
  language:
  # render true/false
  render:
  # parser (RenderSpider)
  parser:

  search:
    paths:
      - path: 'Home/Search?searchstr={keyword}'
        method: get
  torrents:
    list:
      selector: div.central-container > table > tbody > tr.js-search-results-row
    fields:
      id:
        selector: tr.js-search-results-row
        attribute: data-itemindex
      title:
        selector: 'td:nth-child(1) > a.magnet-link-wrap'
      details:
        selector: 'td:nth-child(1) > a.magnet-link-wrap'
        attribute: href
      download:
        selector: 'td:nth-child(1) > a.js-magnet.magnet-link'
        attribute: data-clipboard-text
      date_added:
        selector: 'td:nth-child(3)'
      size:
        selector: 'td:nth-child(2)'
      downloadvolumefactor:
        case:
          '*': 0
      uploadvolumefactor:
        case:
          '*': 1










